# Generated by Django 3.1.12 on 2021-06-26 17:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile number: ')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('twilio_id', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('blood_group', models.CharField(default='O+', max_length=5)),
                ('otp', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField()),
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
            ],
        ),
    ]
