# Generated by Django 3.1.12 on 2021-06-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='twilio_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
