# Generated by Django 3.1.12 on 2021-06-26 15:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Donor', max_length=250)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile number: ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('distict', models.CharField(blank=True, max_length=200, null=True)),
                ('subdistrict', models.CharField(blank=True, max_length=200, null=True)),
                ('last_donated', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(max_length=100)),
                ('date_of_joined', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
