# Generated by Django 3.1.12 on 2021-06-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(max_length=100),
        ),
    ]
